### ISSUE TITLE
Instrument Superset with Flagon UserALE.js

### ISSUE THREAD

**Issue by poorejc** [UMD-ARLIS/superset-risc#3]
Add Client Libraries from Flagon UserALE (module or script tag) into relevant Superset libraries and demonstrate hello world with logs generated from actions in the client.

**Comment by ploats** [comment]
Instrumented by creating a new docker-compose file. UserALE js files are assigned into superset/static and the javascript to enable it is placed in superset/templates in the file tail_js_custom_extra.html
